---
driver:
  name: ec2
  aws_ssh_key_id: MyEC2Keypair
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-0d389e0315ec7f096
  instance_type: t2.micro
  image_id: ami-05ad3e9ea4dcd9863
  security_group_ids: ["sg-0b88665f09978c8db"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: ssh/MyEC2Keypair.pem

platforms:
  - name: windows-2012r2

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes: